### ISSUE TITLE
Required files for melanoma example

### ISSUE THREAD

**Issue by anglixue** [KChen-lab/marker-selection#4]
Hi, I am trying to run the example in
https://htmlpreview.github.io/?https://github.com/KChen-lab/SCMER/blob/master/notebooks/melanoma-gpu-with-batch-in-r.nb.html

I wonder where I can get the input files.

> 'melanoma.txt.gz'
> "genes.txt"
> "melanoma_batches.txt"

Thank you!

**Comment by lshh125** [comment]
Hello,

I believe they are in "https://github.com/KChen-lab/SCMER/tree/master/notebooks". Let me know if those work for you. 

Thanks,
Shaoheng
